/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdGestorDeReuniones.java
 *
 * Created on 07-ene-2013, 11:12:46
 */
package vista.gestorReuniones;

import Util.FechaUtil;
import Util.TablaUtil;
import dominio.Asamblea;
import dominio.AsistenciaAsamblea;
import dominio.Asociado;
import dominio.OrdenDia;
import dominio.dao.AsambleaDao;
import dominio.dao.AsistenciaAsambleaDao;
import dominio.dao.AsociadoDao;
import dominio.dao.OrdenDiaDao;
import dominio.dao.imp.AsambleaDaoImp;
import dominio.dao.imp.AsistenciaAsambleaDaoImp;
import dominio.dao.imp.AsociadoDaoImp;

import dominio.dao.imp.OrdenDiaDaoImp;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Pelaez Joel
 */
public class JDAsamblea extends javax.swing.JDialog {
    int botonSeleecionado=0;   //1-crear 2-editar
    int idAsambleaEdit ;
           
    

    DefaultTableModel modelo;
    /** Creates new form JdGestorDeReuniones */
    public JDAsamblea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    public JDAsamblea(java.awt.Frame parent, boolean modal,int op) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nueva Asamblea");
        this.botonSeleecionado= op;
        
        // para crear una nueva asamblea  no debe cargarse los asociado en ese instante
        tbPanelAsistencia.setEnabledAt(1, false); // inhablilito la pestaña asistencia 
        tbPanelAsistencia.setTitleAt(1, "");
        
        // para crear una nueva asamblea  no debe cargarse el orden del dia 
        tbPanelAsistencia.setEnabledAt(2, false);// inhabilito la pestaña orden del dia
        tbPanelAsistencia.setTitleAt(2, "");
        
       
//        configurarVentana();
    }

    JDAsamblea(java.awt.Frame parent, boolean modal, int idAsamblea,int op) {
        // este constructor se utiliza para ver una asamblea ya creada
        
       
         super(parent, modal);
        initComponents();
        this.setTitle("Asamblea");
        //configuraacion de la ventana
        //Orden del dia
        panelTema.setVisible(false);
        panelSolucionTema.setVisible(false);
  
         
        this.botonSeleecionado= op;
        this.idAsambleaEdit= idAsamblea;
        
        // cargar en la ventana con los valores guardados
        AsambleaDao asambleas = new AsambleaDaoImp();
        Asamblea asamblea = asambleas.getAsamblea(idAsamblea);
        
        
        
        //paso los datos a la  ventana configuracion asamblea
        int indexTipoAsmablea = getIndexCmbTipoAsamblea(asamblea.getTipoAsamblea().toString());
        String lugar = asamblea.getLugar();
        Date fecha = asamblea.getFecha();
                
         txtLugar.setText(lugar);
         cmbElegirAsamblea.setSelectedIndex(indexTipoAsmablea);
         fechaAsamblea.setDate(fecha);
        //..................... 
            
        // paso los datos de la tabla ASISTENCIA_ASAMBLEA a la Jtable asistencia
                     
            TablaUtil.prepararTablaAsambleaAsociado(modelo, tblAsistencia);
            modelo = (DefaultTableModel)tblAsistencia.getModel();
            for (AsistenciaAsamblea asistAsamblea : asamblea.getAsistenciaAsambleas()) {
                Asociado a = asistAsamblea.getAsociados();
                // estos datos deben pasarse a la tabla
                int idAsociado = a.getIdAsociado();
                String nombreAsociado = a.getNombreAsociado()+"  "+a.getApellidoAsociado();
                String horaEntrada = FechaUtil.getHora(asistAsamblea.getHoraLlegada());
                String horaSalida = FechaUtil.getHora(asistAsamblea.getHoraSalida());
               
               Object[] filaAsociado = {idAsociado,nombreAsociado,horaEntrada,horaSalida};
               modelo.addRow(filaAsociado);
               
               }
            
            // paso los datos del orden del dia
            Set<OrdenDia> listaOrdenDia = asamblea.getOrdenDias();
           TablaUtil.prepararTablaOrdendelDia(modelo, tablaOrdenDia);
           TablaUtil.cargarModeloOrdenDelDia(modelo,listaOrdenDia , tablaOrdenDia); 
            
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        tbPanelAsistencia = new org.edisoncor.gui.tabbedPane.TabbedPaneVertical();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fechaAsamblea = new com.toedter.calendar.JDateChooser();
        cmbHoraIninicio = new javax.swing.JComboBox();
        cmbMinInicio = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtObservacion = new org.jdesktop.swingx.JXEditorPane();
        txtLugar = new org.edisoncor.gui.textField.TextFieldRectIcon();
        btnDireccion = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cmbHoraFin = new javax.swing.JComboBox();
        cmbMinFin = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbElegirAsamblea = new javax.swing.JComboBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaOrdenDia = new javax.swing.JTable();
        panelTema = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtTema = new javax.swing.JEditorPane();
        panelSolucionTema = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSolucionTema = new javax.swing.JEditorPane();
        btnEditarTema = new javax.swing.JButton();
        btnAgregarTema = new javax.swing.JButton();
        btnGuardarTema = new javax.swing.JButton();
        btnSalirOrdenDia = new javax.swing.JButton();
        panelAsistencia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsistencia = new javax.swing.JTable();
        btnEntrada = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPresente = new javax.swing.JLabel();
        lblAusente = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jXTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbPanelAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        tbPanelAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Fecha de la  reunion:");

        jLabel7.setText("Hora Inicio:");

        jLabel8.setText("Lugar:");

        jLabel9.setText("Observacion: ");

        cmbHoraIninicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        cmbMinInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel10.setText("hs");

        jLabel11.setText("min");

        jScrollPane3.setViewportView(txtObservacion);

        btnDireccion.setText("Cargar Direccion..");

        jLabel12.setText("Hora Fin:");

        cmbHoraFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        cmbMinFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel1.setText(" Tipo de Asamblea");

        cmbElegirAsamblea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELEGIR", "ORDINARIA", "EXTRAORDINARIA" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Asociado", "direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane7.setViewportView(jTable1);

        jLabel13.setText("hs");

        jLabel14.setText("min");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbElegirAsamblea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(fechaAsamblea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmbHoraIninicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cmbMinInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cmbHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(cmbMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11))
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(btnDireccion)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cmbElegirAsamblea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(fechaAsamblea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbHoraIninicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbMinInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cmbHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cmbMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnDireccion)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbPanelAsistencia.addTab("Configuracion", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaOrdenDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro ", "Tema", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOrdenDia.setGridColor(new java.awt.Color(255, 255, 255));
        tablaOrdenDia.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tablaOrdenDia);
        tablaOrdenDia.getAccessibleContext().setAccessibleParent(jLabel1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 492, 77));

        panelTema.setBackground(new java.awt.Color(255, 255, 255));
        panelTema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jScrollPane5.setViewportView(txtTema);

        javax.swing.GroupLayout panelTemaLayout = new javax.swing.GroupLayout(panelTema);
        panelTema.setLayout(panelTemaLayout);
        panelTemaLayout.setHorizontalGroup(
            panelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTemaLayout.setVerticalGroup(
            panelTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panelTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        panelSolucionTema.setBackground(new java.awt.Color(255, 255, 255));
        panelSolucionTema.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solucion del Tema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jScrollPane6.setViewportView(txtSolucionTema);

        javax.swing.GroupLayout panelSolucionTemaLayout = new javax.swing.GroupLayout(panelSolucionTema);
        panelSolucionTema.setLayout(panelSolucionTemaLayout);
        panelSolucionTemaLayout.setHorizontalGroup(
            panelSolucionTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolucionTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSolucionTemaLayout.setVerticalGroup(
            panelSolucionTemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolucionTemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panelSolucionTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, -1, 110));

        btnEditarTema.setText("EditarTema");
        btnEditarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTemaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 128, -1, -1));

        btnAgregarTema.setText("Agregar un Tema");
        btnAgregarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTemaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 128, -1, -1));

        btnGuardarTema.setText("Guardar Tema");
        btnGuardarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTemaActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 128, -1, -1));

        btnSalirOrdenDia.setText("Salir");
        jPanel3.add(btnSalirOrdenDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 441, -1, -1));

        tbPanelAsistencia.addTab("Orden del Dia", jPanel3);

        panelAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        panelAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Asociado", "Hora Inicio", "hora Salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAsistencia);

        btnEntrada.setText("Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");

        btnSalida.setText("Salida ");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad de Presentes:");

        jLabel3.setText("Cantidad de Ausentes:");

        lblPresente.setText("0");

        lblAusente.setText("0");

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAsistenciaLayout = new javax.swing.GroupLayout(panelAsistencia);
        panelAsistencia.setLayout(panelAsistenciaLayout);
        panelAsistenciaLayout.setHorizontalGroup(
            panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsistenciaLayout.createSequentialGroup()
                .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsistenciaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelAsistenciaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAusente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panelAsistenciaLayout.setVerticalGroup(
            panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsistenciaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsistenciaLayout.createSequentialGroup()
                        .addComponent(btnEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAusente))
                .addGap(15, 15, 15))
        );

        tbPanelAsistencia.addTab("Asistencia", panelAsistencia);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Imprimir");
        jToolBar1.add(btnImprimir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(tbPanelAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbPanelAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnEditarActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    //CAPTURAR LOS DATOS DE CONFIGUARACION DE LA ASAMBLEA
    if (botonSeleecionado==1) {// se crea una asamblea
        String tipoAsablea =  cmbElegirAsamblea.getSelectedItem().toString();
        Date fechaAsamb =  fechaAsamblea.getDate();
        
        String horaIni= cmbHoraIninicio.getSelectedItem().toString()+":"+cmbMinInicio.getSelectedItem().toString();
        Date horaInicio = Util.FechaUtil.getHora(horaIni);
        
        String horaFi= cmbHoraFin.getSelectedItem().toString()+":"+cmbMinFin.getSelectedItem().toString();
        Date horaFin = Util.FechaUtil.getHora(horaFi);
        
        String lugar = txtLugar.getText();
        String obsercacion = txtObservacion.getText();
        
        // guardo la asamblea en la bd
        AsambleaDao Asambleas = new AsambleaDaoImp();
        Asamblea a = new Asamblea(tipoAsablea, fechaAsamb, horaInicio, horaFin, 0, lugar, null, null);
        Asambleas.addAsamblea(a);
    
    
    }else{
       if(botonSeleecionado==2){  //editar
        // capturar los y datos de la tabla asistencia 
           modelo= (DefaultTableModel) tblAsistencia.getModel();
           if (modelo.getRowCount()!=0) { // si contiene datos la tabla entonces guardarlo
               AsambleaDao asambleas = new AsambleaDaoImp();
               AsociadoDao asociados = new AsociadoDaoImp();
               AsistenciaAsambleaDao asistenciasAsamblea = new AsistenciaAsambleaDaoImp();
               Asamblea asamblea = asambleas.getAsamblea(idAsambleaEdit);
               
               Asociado asocidado;
               for (int fila = 1; fila < modelo.getRowCount(); fila++) {
                   int idAsociado = Integer.parseInt(modelo.getValueAt(fila, 0).toString());
                   asocidado = asociados.getAsociado(idAsociado);
                   Date horaEntrada = FechaUtil.getHora(modelo.getValueAt(fila, 2).toString());
                   Date horaSalida = FechaUtil.getHora(modelo.getValueAt(fila, 3).toString());
                   AsistenciaAsamblea asistenciaAsamblea = new AsistenciaAsamblea(asocidado, asamblea, horaEntrada, horaSalida);
                   asistenciasAsamblea.addAsistenciaAsamblea(asistenciaAsamblea);

               }
           }
          
          //capturar los datos del orden del dia
        
        
        
        
       } 
    }
    
    
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
    AsociadoDao asociados = new AsociadoDaoImp();
    List<Asociado> listaAsociado =  asociados.listarAsociados();
    TablaUtil.prepararTablaAsambleaAsociado(modelo, tblAsistencia);

    TablaUtil.cargarModeloAsambleaAsociado(modelo, listaAsociado,tblAsistencia);
}//GEN-LAST:event_btnListarActionPerformed

private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
   
     TablaUtil.setHoraenTablaAsistencia(modelo, tblAsistencia, 2); // columna=3  hora entrada
           
        
}//GEN-LAST:event_btnEntradaActionPerformed

private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
 TablaUtil.setHoraenTablaAsistencia(modelo, tblAsistencia, 3);// columna=4 hora salida
    
 
}//GEN-LAST:event_btnSalidaActionPerformed

private void btnAgregarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTemaActionPerformed
   panelTema.setVisible(true);
   panelSolucionTema.setVisible(true);
   btnEditarTema.setEnabled(false);
   
    
}//GEN-LAST:event_btnAgregarTemaActionPerformed
private void borrarCajaTemaSolucion(){
    
    txtTema.setText("");
    txtSolucionTema.setText("");
    panelTema.setVisible(false);
   panelSolucionTema.setVisible(false);
}
private void btnGuardarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTemaActionPerformed
   OrdenDiaDao ordenes = new OrdenDiaDaoImp();
   AsambleaDao asambleas = new AsambleaDaoImp();
   Asamblea a = asambleas.getAsamblea(idAsambleaEdit);
   OrdenDia orden = new OrdenDia(a,txtTema.getText(), txtSolucionTema.getText());
   ordenes.addOrdenDia(orden);
  
   //borro las cajas
    borrarCajaTemaSolucion();
        
    
    
   Set<OrdenDia> listaOrden = a.getOrdenDias();
   TablaUtil.prepararTablaOrdendelDia(modelo, tablaOrdenDia);
   TablaUtil.cargarModeloOrdenDelDia(modelo, listaOrden, tablaOrdenDia);
   
   //activos los botones
   btnAgregarTema.setEnabled(true);
   btnEditarTema.setEnabled(true);
}//GEN-LAST:event_btnGuardarTemaActionPerformed

private void btnEditarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTemaActionPerformed
    
    int fila = tablaOrdenDia.getSelectedRow();
        if (fila== -1) {
            // no se selecciono ninguna fila de la lista
            JOptionPane.showMessageDialog(null, "debes seleccionar un Tema ", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        } else {
            //inactivo el boton agregar
            btnAgregarTema.setEnabled(false);
            // cargar los datos de la tabla a la caja de texto
            modelo= (DefaultTableModel) tablaOrdenDia.getModel();
            String tema = modelo.getValueAt(fila, 1) .toString();
            String solucion = modelo.getValueAt(fila, 2).toString();
           
            txtTema.setText(tema);
            txtSolucionTema.setText(solucion);
            panelTema.setVisible(true);
            panelSolucionTema.setVisible(true);
        }

}//GEN-LAST:event_btnEditarTemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDAsamblea dialog = new JDAsamblea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTema;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnDireccion;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarTema;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarTema;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSalirOrdenDia;
    private javax.swing.JComboBox cmbElegirAsamblea;
    private javax.swing.JComboBox cmbHoraFin;
    private javax.swing.JComboBox cmbHoraIninicio;
    private javax.swing.JComboBox cmbMinFin;
    private javax.swing.JComboBox cmbMinInicio;
    private com.toedter.calendar.JDateChooser fechaAsamblea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JLabel lblAusente;
    private javax.swing.JLabel lblPresente;
    private javax.swing.JPanel panelAsistencia;
    private javax.swing.JPanel panelSolucionTema;
    private javax.swing.JPanel panelTema;
    private javax.swing.JTable tablaOrdenDia;
    private org.edisoncor.gui.tabbedPane.TabbedPaneVertical tbPanelAsistencia;
    private javax.swing.JTable tblAsistencia;
    private org.edisoncor.gui.textField.TextFieldRectIcon txtLugar;
    private org.jdesktop.swingx.JXEditorPane txtObservacion;
    private javax.swing.JEditorPane txtSolucionTema;
    private javax.swing.JEditorPane txtTema;
    // End of variables declaration//GEN-END:variables

    private void configurarVentana() {
        TableColumn check = tblAsistencia.getColumnModel().getColumn(1);
        JCheckBox checkbox = new JCheckBox();
        check.setCellEditor(new DefaultCellEditor(checkbox));

    }
    private int getIndexCmbTipoAsamblea(String tipo){
        int index=0;
        if (tipo.equalsIgnoreCase("ORDINARIA")) {
            index =1;
        } else {
            if (tipo.equalsIgnoreCase("EXTRAORDINARIA")) {
                index=2;
            }
        }
        return index;
    }
}
