/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDGestordeAsamblea.java
 *
 * Created on 24-feb-2013, 22:55:29
 */
package vista.gestorReuniones;

import Util.TablaUtil;
import dominio.Asamblea;
import dominio.AsistenciaAsamblea;
import dominio.Asociado;
import dominio.dao.AsambleaDao;
import dominio.dao.AsociadoDao;
import dominio.dao.imp.AsambleaDaoImp;
import dominio.dao.imp.AsociadoDaoImp;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class JDGestordeAsamblea extends javax.swing.JDialog {
    
    DefaultTableModel modelo ;

    /** Creates new form JDGestordeAsamblea */
    public JDGestordeAsamblea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsamblea = new javax.swing.JTable();
        btnNuevaAsamblea = new javax.swing.JButton();
        btnVerAsamblea = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor de Asamblea");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAsamblea.setForeground(new java.awt.Color(0, 51, 51));
        tablaAsamblea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro ", "Tipo de Asamblea", "Fecha", "Hora", "Lugar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAsamblea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 567, 259));

        btnNuevaAsamblea.setText("Nueva Asamblea");
        btnNuevaAsamblea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaAsambleaActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevaAsamblea, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        btnVerAsamblea.setText("Seleccionar");
        btnVerAsamblea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAsambleaActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerAsamblea, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 104, -1));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel2.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 107, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODO", "TIPO", "FECHA" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 95, -1));

        jLabel1.setText("Filtrar por: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 75, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnNuevaAsambleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaAsambleaActionPerformed
     //  mando el parametro 1 para que la ventana nuevaAsamblea identifiqe que se usara para crear una asamblea
     JDAsamblea nuevaAsamblea = new JDAsamblea(null,true,1);
     nuevaAsamblea.setLocationRelativeTo(this);
     nuevaAsamblea.setVisible(true);    
     
  
}//GEN-LAST:event_btnNuevaAsambleaActionPerformed

private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
    // traer toda las asambleas de la tabla asamblea
    AsambleaDao asambleas = new AsambleaDaoImp();
    List<Asamblea> listaAsamblea =  asambleas.listarAsamblea();
    TablaUtil.prepararTablaAsambleas(modelo, tablaAsamblea);
    TablaUtil.cargarModeloAsambleas(modelo, listaAsamblea,tablaAsamblea);
   System.out.print(Calendar.getInstance().get(Calendar.HOUR));
   System.out.print(Calendar.getInstance().get(Calendar.MINUTE));
   System.out.print(Calendar.getInstance().get(Calendar.DATE));
   System.out.print(Calendar.getInstance().get(Calendar.DATE));
    // falta agregar filtros de busquedas...(tipo , fecha,etc )
}//GEN-LAST:event_btnListarActionPerformed

private void btnVerAsambleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsambleaActionPerformed

     int fila = tablaAsamblea.getSelectedRow();
        if (fila== -1) {
            // no se selecciono ninguna fila de la lista
            JOptionPane.showMessageDialog(null, "debes seleccionar una Asamblea ", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        } else {
            //ir a la Asamblea pasando los parametros de la tabla
            //paso los datos de la asamblea
            modelo = (DefaultTableModel)tablaAsamblea.getModel();
            int idAsamblea = Integer.parseInt(modelo.getValueAt(fila, 0).toString());
            JDAsamblea verAsamblea = new JDAsamblea(null,true,idAsamblea,2);
            verAsamblea.setLocationRelativeTo(this);
            verAsamblea.setVisible(true);
            
            
        }
    
}//GEN-LAST:event_btnVerAsambleaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGestordeAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGestordeAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGestordeAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGestordeAsamblea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDGestordeAsamblea dialog = new JDGestordeAsamblea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNuevaAsamblea;
    private javax.swing.JButton btnVerAsamblea;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsamblea;
    // End of variables declaration//GEN-END:variables
}
