package dominio;
// Generated 24-feb-2013 21:35:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Asamblea generated by hbm2java
 */
public class Asamblea  implements java.io.Serializable {


     private Integer idAsamblea;
     private String tipoAsamblea;
     private Date fecha;
     private Date horaInicio;
     private Date horaFin;
     private int cantAsociado;
     private String lugar;
     private Set<OrdenDia> ordenDias = new HashSet<OrdenDia>(0);
     private Set<AsistenciaAsamblea> asistenciaAsambleas = new HashSet<AsistenciaAsamblea>(0);

    public Asamblea() {
    }

	
    public Asamblea(Date fecha, Date horaInicio, Date horaFin, int cantAsociado) {
        this.fecha = fecha;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
        this.cantAsociado = cantAsociado;
    }
    public Asamblea(String tipoAsamblea, Date fecha, Date horaInicio, Date horaFin, int cantAsociado, String lugar, Set<OrdenDia> ordenDias, Set<AsistenciaAsamblea> asistenciaAsambleas) {
       this.tipoAsamblea = tipoAsamblea;
       this.fecha = fecha;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.cantAsociado = cantAsociado;
       this.lugar = lugar;
       this.ordenDias = ordenDias;
       this.asistenciaAsambleas = asistenciaAsambleas;
    }
   
    public Integer getIdAsamblea() {
        return this.idAsamblea;
    }
    
    public void setIdAsamblea(Integer idAsamblea) {
        this.idAsamblea = idAsamblea;
    }
    public String getTipoAsamblea() {
        return this.tipoAsamblea;
    }
    
    public void setTipoAsamblea(String tipoAsamblea) {
        this.tipoAsamblea = tipoAsamblea;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public int getCantAsociado() {
        return this.cantAsociado;
    }
    
    public void setCantAsociado(int cantAsociado) {
        this.cantAsociado = cantAsociado;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set<OrdenDia> getOrdenDias() {
        return this.ordenDias;
    }
    
    public void setOrdenDias(Set<OrdenDia> ordenDias) {
        this.ordenDias = ordenDias;
    }
    public Set<AsistenciaAsamblea> getAsistenciaAsambleas() {
        return this.asistenciaAsambleas;
    }
    
    public void setAsistenciaAsambleas(Set<AsistenciaAsamblea> asistenciaAsambleas) {
        this.asistenciaAsambleas = asistenciaAsambleas;
    }




}


