package dominio;
// Generated 24-feb-2013 21:35:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Asociado generated by hbm2java
 */
public class Asociado  implements java.io.Serializable {


     private Integer idAsociado;
     private Categoria categoria;
     private String nombreAsociado;
     private String apellidoAsociado;
     private int dni;
     private long cuil;
     private String responsabilidad;
     private String nacionalidad;
     private String estadoCivil;
     private String calle;
     private String barrio;
     private String ciudad;
     private String provincia;
     private Integer telefono;
     private Integer celular;
     private Integer fax;
     private String email;
     private String sexo;
     private Date fechaNacimiento;
     private Integer cantidadHijo;
     private Integer numeroActaAsamblea;
     private Integer nroFolio;
     private Date fechaIngreso;
     private Date fechaEgreso;
     private String causaEgreso;
     private Integer cuotasSuscriptas;
     private Integer cuotasIntegradas;
     private Set<AsistenciaAsamblea> asistenciaAsambleas = new HashSet<AsistenciaAsamblea>(0);

    public Asociado() {
    }

	
    public Asociado(int dni, long cuil,String nombre , String apellido) {
        this.dni = dni;
        this.cuil = cuil;
        this.nombreAsociado= nombre;
        this.apellidoAsociado=apellido;
    }
    public Asociado(Categoria categoria, String nombreAsociado, String apellidoAsociado, int dni, long cuil, String responsabilidad, String nacionalidad, String estadoCivil, String calle, String barrio, String ciudad, String provincia, Integer telefono, Integer celular, Integer fax, String email, String sexo, Date fechaNacimiento, Integer cantidadHijo, Integer numeroActaAsamblea, Integer nroFolio, Date fechaIngreso, Date fechaEgreso, String causaEgreso, Integer cuotasSuscriptas, Integer cuotasIntegradas, Set<AsistenciaAsamblea> asistenciaAsambleas) {
       this.categoria = categoria;
       this.nombreAsociado = nombreAsociado;
       this.apellidoAsociado = apellidoAsociado;
       this.dni = dni;
       this.cuil = cuil;
       this.responsabilidad = responsabilidad;
       this.nacionalidad = nacionalidad;
       this.estadoCivil = estadoCivil;
       this.calle = calle;
       this.barrio = barrio;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.telefono = telefono;
       this.celular = celular;
       this.fax = fax;
       this.email = email;
       this.sexo = sexo;
       this.fechaNacimiento = fechaNacimiento;
       this.cantidadHijo = cantidadHijo;
       this.numeroActaAsamblea = numeroActaAsamblea;
       this.nroFolio = nroFolio;
       this.fechaIngreso = fechaIngreso;
       this.fechaEgreso = fechaEgreso;
       this.causaEgreso = causaEgreso;
       this.cuotasSuscriptas = cuotasSuscriptas;
       this.cuotasIntegradas = cuotasIntegradas;
       this.asistenciaAsambleas = asistenciaAsambleas;
    }
   
    public Integer getIdAsociado() {
        return this.idAsociado;
    }
    
    public void setIdAsociado(Integer idAsociado) {
        this.idAsociado = idAsociado;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreAsociado() {
        return this.nombreAsociado;
    }
    
    public void setNombreAsociado(String nombreAsociado) {
        this.nombreAsociado = nombreAsociado;
    }
    public String getApellidoAsociado() {
        return this.apellidoAsociado;
    }
    
    public void setApellidoAsociado(String apellidoAsociado) {
        this.apellidoAsociado = apellidoAsociado;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public long getCuil() {
        return this.cuil;
    }
    
    public void setCuil(long cuil) {
        this.cuil = cuil;
    }
    public String getResponsabilidad() {
        return this.responsabilidad;
    }
    
    public void setResponsabilidad(String responsabilidad) {
        this.responsabilidad = responsabilidad;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public Integer getFax() {
        return this.fax;
    }
    
    public void setFax(Integer fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Integer getCantidadHijo() {
        return this.cantidadHijo;
    }
    
    public void setCantidadHijo(Integer cantidadHijo) {
        this.cantidadHijo = cantidadHijo;
    }
    public Integer getNumeroActaAsamblea() {
        return this.numeroActaAsamblea;
    }
    
    public void setNumeroActaAsamblea(Integer numeroActaAsamblea) {
        this.numeroActaAsamblea = numeroActaAsamblea;
    }
    public Integer getNroFolio() {
        return this.nroFolio;
    }
    
    public void setNroFolio(Integer nroFolio) {
        this.nroFolio = nroFolio;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaEgreso() {
        return this.fechaEgreso;
    }
    
    public void setFechaEgreso(Date fechaEgreso) {
        this.fechaEgreso = fechaEgreso;
    }
    public String getCausaEgreso() {
        return this.causaEgreso;
    }
    
    public void setCausaEgreso(String causaEgreso) {
        this.causaEgreso = causaEgreso;
    }
    public Integer getCuotasSuscriptas() {
        return this.cuotasSuscriptas;
    }
    
    public void setCuotasSuscriptas(Integer cuotasSuscriptas) {
        this.cuotasSuscriptas = cuotasSuscriptas;
    }
    public Integer getCuotasIntegradas() {
        return this.cuotasIntegradas;
    }
    
    public void setCuotasIntegradas(Integer cuotasIntegradas) {
        this.cuotasIntegradas = cuotasIntegradas;
    }
    public Set<AsistenciaAsamblea> getAsistenciaAsambleas() {
        return this.asistenciaAsambleas;
    }
    
    public void setAsistenciaAsambleas(Set<AsistenciaAsamblea> asistenciaAsambleas) {
        this.asistenciaAsambleas = asistenciaAsambleas;
    }




}


