package dominio;
// Generated 24-feb-2013 21:35:58 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombreCategoria;
     private String descripcionCat;
     private Set<Asociado> asociadoses = new HashSet<Asociado>(0);

    public Categoria() {
    }

    public Categoria(String nombreCategoria, String descripcionCat, Set<Asociado> asociadoses) {
       this.nombreCategoria = nombreCategoria;
       this.descripcionCat = descripcionCat;
       this.asociadoses = asociadoses;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public String getDescripcionCat() {
        return this.descripcionCat;
    }
    
    public void setDescripcionCat(String descripcionCat) {
        this.descripcionCat = descripcionCat;
    }
    public Set<Asociado> getAsociadoses() {
        return this.asociadoses;
    }
    
    public void setAsociadoses(Set<Asociado> asociadoses) {
        this.asociadoses = asociadoses;
    }




}


