package dominio;
// Generated 24-feb-2013 21:35:58 by Hibernate Tools 3.2.1.GA



/**
 * OrdenDia generated by hbm2java
 */
public class OrdenDia  implements java.io.Serializable {


     private Integer idOd;
     private Asamblea asamblea;
     private String tema;
     private String conclusionTema;

    public OrdenDia() {
    }

    public OrdenDia(Asamblea asamblea, String tema, String conclusionTema) {
       this.asamblea = asamblea;
       this.tema = tema;
       this.conclusionTema = conclusionTema;
    }
   
    public Integer getIdOd() {
        return this.idOd;
    }
    
    public void setIdOd(Integer idOd) {
        this.idOd = idOd;
    }
    public Asamblea getAsamblea() {
        return this.asamblea;
    }
    
    public void setAsamblea(Asamblea asamblea) {
        this.asamblea = asamblea;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public String getConclusionTema() {
        return this.conclusionTema;
    }
    
    public void setConclusionTema(String conclusionTema) {
        this.conclusionTema = conclusionTema;
    }




}


