CREATE DATABASE COOPERATIVA;
USE COOPERATIVA

--tabla de categorias de monotributo
CREATE TABLE CATEGORIA(
       ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
	   NOMBRE_CATEGORIA VARCHAR(2) NULL,
       DESCRIPCION_CAT VARCHAR(100) NULL,
	   PRIMARY KEY (ID_CATEGORIA)
       ) ENGINE=InnoDB;

CREATE TABLE ASOCIADOS (
       ID_ASOCIADO INT NOT NULL AUTO_INCREMENT,
       NOMBRE_ASOCIADO VARCHAR(50) NULL,
       APELLIDO_ASOCIADO VARCHAR(50) NULL,
	   DNI INT NOT NULL,
       CUIL BIGINT NOT NULL,
	   RESPONSABILIDAD VARCHAR(30) NULL,
	   NACIONALIDAD VARCHAR(30) NULL,
	   ESTADO_CIVIL VARCHAR(10) NULL,
	   CALLE VARCHAR(100) NULL,
	   BARRIO VARCHAR(100) NULL,
	   CIUDAD VARCHAR(60) NULL,
	   PROVINCIA VARCHAR(60) NULL,
	   TELEFONO INT NULL,
	   CELULAR INT NULL,
	   FAX INT NULL,
	   EMAIL VARCHAR(50) NULL,
	   SEXO VARCHAR(15) NULL,
	   FECHA_NACIMIENTO DATE NULL,
	   CANTIDAD_HIJO INT NULL,
	   NUMERO_ACTA_ASAMBLEA INT NULL,
	   NRO_FOLIO INT NULL,
	   FECHA_INGRESO DATE NULL,
	   FECHA_EGRESO DATE NULL,
	   CAUSA_EGRESO VARCHAR(200) NULL,
	   ID_CATEGORIA INT,
	   CUOTAS_SUSCRIPTAS INT NULL,
	   CUOTAS_INTEGRADAS INT NULL,
       PRIMARY KEY (ID_ASOCIADO),
	   FOREIGN KEY (ID_CATEGORIA)
	   REFERENCES CATEGORIA(ID_CATEGORIA)
	   ON DELETE CASCADE
	   ON UPDATE CASCADE
       ) ENGINE=InnoDB;

	   
--para el libro de asamblea
CREATE TABLE ASAMBLEA(
       ID_ASAMBLEA INT NOT NULL AUTO_INCREMENT,
       TIPO_ASAMBLEA VARCHAR(100) NULL,
	   FECHA DATE NOT NULL,
       HORA_INICIO TIME NOT NULL,
       HORA_FIN TIME NOT NULL,
       CANT_ASOCIADO INT NOT NULL,
	   LUGAR VARCHAR(200) NULL,
	   PRIMARY KEY (ID_ASAMBLEA)
       ) ENGINE=InnoDB;
	   
--tabla orden del día(cada orden tiene varios temas)
CREATE TABLE ORDEN_DIA(
       ID_OD INT NOT NULL AUTO_INCREMENT,
	   TEMA VARCHAR(100) NULL,
	   CONCLUSION_TEMA VARCHAR(150) NULL,
	   ID_ASAMBLEA INT,
	   PRIMARY KEY (ID_OD),
	   FOREIGN KEY (ID_ASAMBLEA)
	   REFERENCES ASAMBLEA(ID_ASAMBLEA)
	   ON DELETE CASCADE
	   ON UPDATE CASCADE
       ) ENGINE=InnoDB;
	   
CREATE TABLE ASISTENCIA_ASAMBLEA (
     ID_ASISTENCIA_A INT NOT NULL AUTO_INCREMENT,
     HORA_LLEGADA TIME  NULL,
     HORA_SALIDA TIME  NULL,
     ID_ASAMBLEA INT,
	 ID_ASOCIADO INT,
	 PRIMARY KEY (ID_ASISTENCIA_A),
     FOREIGN KEY (ID_ASAMBLEA)
     REFERENCES ASAMBLEA(ID_ASAMBLEA)
	 ON DELETE CASCADE
     ON UPDATE CASCADE,
	 FOREIGN KEY (ID_ASOCIADO)
     REFERENCES ASOCIADOS(ID_ASOCIADO)
	 ON DELETE CASCADE
     ON UPDATE CASCADE
     ) ENGINE=InnoDB;