/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDGestorDeAsociado.java
 *
 * Created on 30-dic-2012, 5:00:26
 */
package vista.gestorAsociado;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import vista.gestorReuniones.JDAsamblea;

/**
 *
 * @author Pelaez Joel
 */
public class JDGestorDeAsociado extends javax.swing.JDialog {

    /** Creates new form JDGestorDeAsociado */
    public JDGestorDeAsociado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarVentana();
        this.setVisible(true); 
      
    }

    private void configurarVentana(){
        
//        // estadisitica 
        ImageIcon imgEstadisitica= (ImageIcon)btnEstadisticas.getIcon();//new ImageIcon("src/images/estadistica.jpg");
        Icon iconoEstadisitica = new ImageIcon(imgEstadisitica.getImage().getScaledInstance(btnInfPersonal.getIcon().getIconWidth(), btnInfPersonal.getIcon().getIconHeight(), Image.SCALE_SMOOTH));
        btnEstadisticas.setIcon(iconoEstadisitica);
        
        //informacion personal
        ImageIcon imgInfPers= new ImageIcon("src/images/infPersonal.jpg");
        Icon iconoInfPers = new ImageIcon(imgInfPers.getImage().getScaledInstance(btnInfPersonal.getIcon().getIconWidth(), btnInfPersonal.getIcon().getIconHeight(), Image.SCALE_SMOOTH));
        btnInfPersonal.setIcon(iconoInfPers);
        
        // Aporte 
        ImageIcon imgAporte= new ImageIcon("src/images/aporte2.jpg");
        Icon iconoAporte = new ImageIcon(imgAporte.getImage().getScaledInstance(btnInfPersonal.getIcon().getIconWidth()+5, btnInfPersonal.getIcon().getIconHeight(), Image.SCALE_SMOOTH));
        btnAportes.setIcon(iconoAporte);
        
        //sancion
        ImageIcon imgSancion = new ImageIcon("src/images/descarga.jpg");
        Icon iconSancion = new ImageIcon(imgSancion.getImage().getScaledInstance(btnInfPersonal.getIcon().getIconWidth(), btnInfPersonal.getIcon().getIconHeight(),Image.SCALE_SMOOTH));
        btnSancion.setIcon(iconSancion);
         
        //Asistencia
        ImageIcon imgAsistencia = (ImageIcon) btnAsistencia.getIcon();//new ImageIcon("src/images/reunionsocios.jpg");
        Icon iconAsistencia = new ImageIcon(imgAsistencia.getImage().getScaledInstance(btnInfPersonal.getIcon().getIconWidth()+10, btnInfPersonal.getIcon().getIconHeight(),Image.SCALE_SMOOTH));
        btnAsistencia.setIcon(iconAsistencia);
         
        
         
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        btnInfPersonal = new org.edisoncor.gui.button.ButtonTask();
        btnAsistencia = new org.edisoncor.gui.button.ButtonTask();
        btnAportes = new org.edisoncor.gui.button.ButtonTask();
        btnSancion = new org.edisoncor.gui.button.ButtonTask();
        btnEstadisticas = new org.edisoncor.gui.button.ButtonTask();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asociados");

        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(102, 204, 255));
        panelRectTranslucido1.setColorDeSegundoBorde(new java.awt.Color(204, 204, 255));
        panelRectTranslucido1.setColorPrimario(new java.awt.Color(153, 153, 255));
        panelRectTranslucido1.setColorSecundario(new java.awt.Color(255, 255, 255));

        btnInfPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUsuario.jpg"))); // NOI18N
        btnInfPersonal.setText("Registro");
        btnInfPersonal.setDescription("Personal");
        btnInfPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfPersonalActionPerformed(evt);
            }
        });

        btnAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reunionsocios.jpg"))); // NOI18N
        btnAsistencia.setText("Asambleas");
        btnAsistencia.setDescription("Registros");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });

        btnAportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aporte2.jpg"))); // NOI18N
        btnAportes.setText("Aportes");
        btnAportes.setDescription("Personal");
        btnAportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAportesActionPerformed(evt);
            }
        });

        btnSancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descarga.jpg"))); // NOI18N
        btnSancion.setText("Sancion");
        btnSancion.setDescription("Personal");
        btnSancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSancionActionPerformed(evt);
            }
        });

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estadistica.jpg"))); // NOI18N
        btnEstadisticas.setText("Estadistica");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInfPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnInfPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfPersonalActionPerformed
  new JDRegistroAsociado(null, true).setVisible(true);
}//GEN-LAST:event_btnInfPersonalActionPerformed

private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
  
    new vista.gestorReuniones.JDGestordeAsamblea(null, rootPaneCheckingEnabled).setVisible(true);
   
}//GEN-LAST:event_btnAsistenciaActionPerformed

private void btnAportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAportesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnAportesActionPerformed

private void btnSancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSancionActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnSancionActionPerformed

private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGestorDeAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGestorDeAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGestorDeAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGestorDeAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDGestorDeAsociado dialog = new JDGestorDeAsociado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btnAportes;
    private org.edisoncor.gui.button.ButtonTask btnAsistencia;
    private org.edisoncor.gui.button.ButtonTask btnEstadisticas;
    private org.edisoncor.gui.button.ButtonTask btnInfPersonal;
    private org.edisoncor.gui.button.ButtonTask btnSancion;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    // End of variables declaration//GEN-END:variables
}
